"""orchestra.domain 公开 API。"""

from .agent import (
    AgentCapabilities,
    AgentHealth,
    AgentMetrics,
    AgentSelector,
    AgentSpec,
    LivenessProbe,
    Profile,
    Probe,
    Resources,
    RetryPolicy,
)
from .enums import (
    AggregateStrategy,
    AgentStatus,
    ApprovalPolicy,
    BackoffKind,
    CompensationStrategy,
    HealthStatus,
    NotificationChannel,
    NotificationEvent,
    OnFailure,
    OnTimeout,
    OutputStorage,
    ParentClosePolicy,
    Phase,
    Priority,
    Role,
    SideEffect,
    StagePhase,
    StorageClass,
    TriggerKind,
)
from .errors import (
    ApprovalRejected,
    AuthError,
    BudgetExceeded,
    ConfigurationError,
    InvalidInput,
    MCPDisconnect,
    OrchestraError,
    RateLimited,
    SchemaViolation,
    TimeoutError,
    ToolNotAllowed,
    TransientError,
    all_non_retryable_codes,
    get_error_class,
)
from .pipeline import (
    Approval,
    ArtifactRef,
    ArtifactSpec,
    CacheSpec,
    ChildWorkflowRef,
    Compensation,
    CompensationAction,
    DynamicStage,
    GlobalSpec,
    GlobalTimeouts,
    LoopStage,
    Metadata,
    Notification,
    OutputSpec,
    ParameterDef,
    Pipeline,
    PipelineBody,
    PipelineRef,
    PipelineRun,
    PipelineRunSpec,
    PipelineSpec,
    PipelineStatus,
    Retention,
    SecretRef,
    Stage,
    StageStatus,
    StageTimeouts,
    TriggerInfo,
)
from .state import (
    ArtifactReference,
    Checkpoint,
    ProgressInfo,
    StageOutput,
    TaskInput,
    TaskOutput,
    WorkflowState,
)

__all__ = [
    # enums
    "Phase", "StagePhase", "Role", "Priority", "BackoffKind", "AggregateStrategy",
    "OnFailure", "OutputStorage", "StorageClass", "CompensationStrategy",
    "ApprovalPolicy", "OnTimeout", "ParentClosePolicy", "SideEffect",
    "TriggerKind", "NotificationChannel", "NotificationEvent", "HealthStatus", "AgentStatus",
    # errors
    "OrchestraError", "AuthError", "ToolNotAllowed", "InvalidInput", "SchemaViolation",
    "ApprovalRejected", "BudgetExceeded", "ConfigurationError",
    "TransientError", "RateLimited", "TimeoutError", "MCPDisconnect",
    "get_error_class", "all_non_retryable_codes",
    # agent
    "AgentSpec", "Profile", "AgentSelector", "AgentCapabilities", "AgentHealth", "AgentMetrics",
    "Resources", "Probe", "LivenessProbe", "RetryPolicy",
    # pipeline
    "Pipeline", "PipelineRun", "PipelineSpec", "PipelineRunSpec", "PipelineBody",
    "Stage", "StageTimeouts", "OutputSpec", "Approval", "DynamicStage", "LoopStage",
    "ChildWorkflowRef", "Compensation", "CompensationAction", "GlobalSpec", "GlobalTimeouts",
    "SecretRef", "ParameterDef", "Notification", "Retention",
    "ArtifactSpec", "ArtifactRef", "CacheSpec", "Metadata", "PipelineRef", "TriggerInfo",
    "PipelineStatus", "StageStatus",
    # state
    "WorkflowState", "StageOutput", "ArtifactReference", "Checkpoint", "ProgressInfo",
    "TaskInput", "TaskOutput",
]
